# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    
    - name: Prepare Allure history
              run:|
                  rm -r allure-results/*
                  cp -r ./allure-report/history ./allure-results/history
                  rm -r allure-report/*
    
    
    - name: Run Test
    - run: npm run cypress:run
    
    - name: Generate Allure report
      uses: QuintilianoNery/action-allure-report-V2@0.2.0

    - name: Commit report results            
      run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add allure-report -f
                  git add allure-results -f
                  git commit -m "[chore] autogenerate Allure report" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
                  github_token: '${{ secrets.GITHUB_TOKEN }}'
                  force: true
